version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper@sha256:c83977656ae4bb755a6016887b118f171c6b8cf99d03a95e84efdfe7ae5bd454
    ports:
      - 2181:2181
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka@sha256:fcd007cd3c5ad0ff8cc9b92c2746f467afd0db1989563b9ddc513bb8c571a0eb
    ports:
      - 9094:9094
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 30s
      timeout: 10s
      retries: 23
    restart: on-failure
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_offsets_topic_replication_factor: 1

  minio:
    image: minio/minio@sha256:68622c3e49dd98fbbcb8200729297207759d52e3b02d2ed908c1a7ff3b83f3f7
    hostname: minio
    ports:
      - 9000:9000
    restart: on-failure
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_REGION_NAME: dummy_region
    entrypoint: sh
    command: -c 'mkdir -p /data/package-analysis{,-static,-file-writes,-analyzed-packages} && /usr/bin/minio server /data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  analysis:
    image: ghcr.io/khulnasoft-lab/analysis:latest
    privileged: true
    ports:
      - 6060:6060
    restart: unless-stopped
    entrypoint: "/usr/local/bin/worker"
    environment:
      OSSMALWARE_WORKER_SUBSCRIPTION: kafka://worker?topic=workers
      OSSF_MALWARE_NOTIFICATION_TOPIC: kafka://notifications
      OSSF_MALWARE_ANALYSIS_RESULTS: s3://package-analysis?endpoint=minio:9000&disableSSL=true&s3ForcePathStyle=true
      OSSF_MALWARE_STATIC_ANALYSIS_RESULTS: s3://package-analysis-static?endpoint=minio:9000&disableSSL=true&s3ForcePathStyle=true
      OSSF_MALWARE_ANALYSIS_FILE_WRITE_RESULTS: s3://package-analysis-file-writes?endpoint=minio:9000&disableSSL=true&s3ForcePathStyle=true
      OSSF_MALWARE_ANALYZED_PACKAGES: s3://package-analysis-analyzed-packages?endpoint=minio:9000&disableSSL=true&s3ForcePathStyle=true
      OSSF_MALWARE_ANALYSIS_ENABLE_PROFILER: "true"
      KAFKA_BROKERS: kafka:9092
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: dummy_region
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy

  scheduler:
    image: ghcr.io/khulnasoft-lab/scheduler:latest
    entrypoint: "/usr/local/bin/scheduler"
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    environment:
      OSSMALWARE_WORKER_TOPIC: kafka://workers
      OSSMALWARE_SUBSCRIPTION_URL: kafka://worker?topic=package-feeds
      KAFKA_BROKERS: kafka:9092

  feeds:
    image: ghcr.io/khulnasoft-lab/scheduled-feeds:latest
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      PACKAGE_FEEDS_CONFIG_PATH: /config/feeds.yml
    volumes:
      - "./config/:/config/"
